### PR TITLE
added npm shim

### PR DESCRIPTION
**Pull request by jdxcode**
this will make `npm i -g` automatically reshim

https://github.com/rtx-plugins/rtx-nodejs/issues/6

### CODE REVIEW

**Comment by jdxcode** [comment]
@pdecat I'll cut a release with this by eod, once that happens would you mind trying the core plugin to see if it works for you? Just uninstall node/nodejs, enable experimental mode, then run `rtx i node@latest`. You can tell if it is using the core plugin by reading the output of `rtx doctor`.

**Comment by pdecat** [comment]
It's working great, thanks @jdxcode!

**Comment by pdecat** [comment]
FWIW, the difference between node and nodejs core plugins was unclear to me.

From https://github.com/jdxcode/rtx/blob/07160fa309b824c1437dca07d4c53722286e3a39/src/plugins/core/mod.rs#L19-L20 and https://github.com/jdxcode/rtx/blob/07160fa309b824c1437dca07d4c53722286e3a39/src/plugins/core/node.rs#L192

I understand it only concerns the [support for `.node-version`](https://github.com/jdxcode/rtx/blame/v1.29.1/README.md#L549).

Is that right?

**Comment by jdxcode** [comment]
nodejs is hidden to retain compatibility with asdf's name for the plugin

**Pull request merged**
