### PR TITLE
feat: added `rtx activate --status`

### LINKED ISSUE #154: Configuration option to hide a prompt?
When I switch between projects I get the output that looks like this:

```
rtx node@16.19.0 ruby@3.2.1
```

I don't really need this information all the time, is there an option to hide these messages?

### PR DESCRIPTION
**Pull request by jdxcode**
This changes the behavior of activate to default to not displaying the status line.

Fixes #154

### CODE REVIEW

**Comment by tycooon** [comment]
What if some people still like the message? Not sure how to turn it on now 🤔

**Comment by jdxcode** [comment]
huh? it's in the title of this PR: `rtx activate --status`

**Comment by tycooon** [comment]
But I never use the `rtx activate` command 🤔

**Comment by tycooon** [comment]
Actually I do that in my rc-file, sorry :)

**Pull request merged**
